"""Shared pytest setup.

Holds one thing: a SQLite shim for `event_log.sequence`.

Production storage is Postgres, where `sequence` is `GENERATED BY DEFAULT AS
IDENTITY` and the database assigns it (storage/tables.py). SQLite cannot
auto-generate a monotonic value for a *non-primary-key* integer column at all --
`AUTOINCREMENT` only applies to `INTEGER PRIMARY KEY` -- so an insert against the
in-memory test engine would fail the NOT NULL constraint.

The shim lives here, in the test harness, rather than in `append_event`: the
production write path must not carry a dialect branch, and `sequence` must stay
a database-assigned value in the dialect that actually runs in production. This
is the same class of test-harness fidelity fix as the dialect-portable `_UUID`
variant in storage/tables.py (see `docs/decisions/2026-07-22-projections-event-replay.md`).
"""

from __future__ import annotations

from typing import Any

from sqlalchemy import event, func, select
from sqlalchemy.engine import Connection
from sqlalchemy.orm import Mapper

from atlas.storage.tables import EventLog


@event.listens_for(EventLog, "before_insert")
def _assign_sequence_when_dialect_cannot(
    mapper: Mapper[Any], connection: Connection, target: EventLog
) -> None:
    """Fill `sequence` on dialects without identity columns (SQLite in tests).

    `max(sequence) + 1` is not concurrency-safe, but the test engine is a
    single-connection in-memory database, and Postgres -- the only dialect that
    runs concurrently -- never reaches this branch.
    """
    if connection.dialect.supports_identity_columns or target.sequence is not None:
        return
    target.sequence = connection.execute(
        select(func.coalesce(func.max(EventLog.sequence), 0) + 1)
    ).scalar_one()
