"""create event_log

Revision ID: 361d4f411a68
Revises:
Create Date: 2026-07-21 21:11:57.068943

Hand-written rather than autogenerated: there's no live Supabase connection
to reflect against at migration-authoring time, so this mirrors
atlas.storage.tables.EventLog column-for-column instead.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "361d4f411a68"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

event_type_enum = postgresql.ENUM(
    "node_created",
    "node_confirmed",
    "node_edited",
    "node_rejected",
    "edge_created",
    "spec_exported",
    "ingestion_run",
    name="event_type",
)


def upgrade() -> None:
    """Create the append-only event_log table (TRD Sec3.1 Event)."""
    event_type_enum.create(op.get_bind(), checkfirst=True)
    op.create_table(
        "event_log",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            nullable=False,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "event_type",
            postgresql.ENUM(
                "node_created",
                "node_confirmed",
                "node_edited",
                "node_rejected",
                "edge_created",
                "spec_exported",
                "ingestion_run",
                name="event_type",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("payload", postgresql.JSONB(), nullable=False),
        sa.Column("actor", sa.Text(), nullable=False),
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column("workspace_id", postgresql.UUID(as_uuid=True), nullable=False),
    )


def downgrade() -> None:
    """Drop event_log. Destructive -- there is no confirmation-loss guard at
    this layer, so only run this against a disposable/dev database."""
    op.drop_table("event_log")
    event_type_enum.drop(op.get_bind(), checkfirst=True)
