"""add event_log.sequence

Revision ID: 8c41a0b7e2d5
Revises: 361d4f411a68
Create Date: 2026-08-03

Phase 1 slice 1A: once `node_confirmed`/`node_edited`/`node_rejected` events
exist, projection replay order is semantically load-bearing (an edit after a
confirm must win) and wall-clock `timestamp` is not a safe ordering key -- two
events appended in one transaction can share it, and clock adjustment could
reorder them outright. `sequence` is the database-assigned total order of
appends (see `docs/architecture/Phase1_Architecture.md` Sec4.2).

Hand-written, like the initial migration: there's no live Supabase connection to
autogenerate against, so this mirrors atlas.storage.tables.EventLog by hand.

Existing rows are backfilled in `(timestamp, id)` order -- the exact order
`load_projection` used before this column existed -- so replaying a pre-existing
log produces the same projection after the migration as before it.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8c41a0b7e2d5"
down_revision: str | Sequence[str] | None = "361d4f411a68"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Add `sequence`, backfill it, then make it identity-generated + NOT NULL."""
    # Added nullable so the backfill can run against a table that already has
    # rows; an identity column added directly would assign values in physical
    # order, which is close to insertion order but not guaranteed to be it.
    op.add_column("event_log", sa.Column("sequence", sa.BigInteger(), nullable=True))
    op.execute(
        """
        UPDATE event_log
           SET sequence = ordered.row_number
          FROM (
                SELECT id,
                       row_number() OVER (ORDER BY timestamp, id) AS row_number
                  FROM event_log
               ) AS ordered
         WHERE event_log.id = ordered.id
        """
    )
    op.alter_column("event_log", "sequence", nullable=False)
    op.execute("ALTER TABLE event_log ALTER COLUMN sequence ADD GENERATED BY DEFAULT AS IDENTITY")
    # Start the generator past the backfilled values, or the first new append
    # would collide with row 1.
    op.execute(
        """
        SELECT setval(
            pg_get_serial_sequence('event_log', 'sequence'),
            coalesce((SELECT max(sequence) FROM event_log), 0) + 1,
            false
        )
        """
    )
    # Identity is BY DEFAULT (not ALWAYS), so an explicit insert could still
    # duplicate a value; the constraint makes the total order actually total.
    op.create_unique_constraint("uq_event_log_sequence", "event_log", ["sequence"])
    # Serves the replay query: `where workspace_id = :w order by sequence`.
    op.create_index("ix_event_log_workspace_sequence", "event_log", ["workspace_id", "sequence"])


def downgrade() -> None:
    """Drop the sequence column. Loses append order for any rows written after
    the upgrade -- replay falls back to `(timestamp, id)`, which is what the
    pre-Phase-1 code ordered by."""
    op.drop_index("ix_event_log_workspace_sequence", table_name="event_log")
    op.drop_constraint("uq_event_log_sequence", "event_log", type_="unique")
    op.drop_column("event_log", "sequence")
