"""workspace RBAC + row-level security

Revision ID: b7c2f1a45d90
Revises: 8c41a0b7e2d5
Create Date: 2026-08-11

Phase 1 slice 1D. Three things:

1. **`workspace` and `workspace_member`** -- the tenant boundary becomes real
   data instead of the `DEFAULT_WORKSPACE_ID` sentinel every Phase 0 write
   stamped.

2. **The sentinel becomes a provisioned row, keeping its id.**
   `docs/decisions/2026-07-21-phase0-default-workspace-id.md` planned to
   "reassign every nil-workspace event to the real workspace". Seeding the row
   with the nil UUID reaches the same end state without rewriting a single row of
   an append-only log that is the system's source of truth -- rewriting history
   to tidy an id would be a worse trade than keeping a memorable one.

3. **Row-level security on `event_log`** (TRD Sec9). Application code already
   filters by `workspace_id`; the policy is the second lock, so a query that
   *forgets* the filter returns nothing rather than another tenant's rows. It
   reads `current_setting('atlas.workspace_id')`, which
   `storage/rbac.py::scope_to_workspace` sets per transaction.

   `workspace` and `workspace_member` are deliberately **not** under RLS: they
   are what resolve a request to a workspace in the first place, so putting them
   behind a setting that isn't known yet is circular.

Hand-written rather than autogenerated, like the migrations before it -- there is
no live database to reflect against at authoring time.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "b7c2f1a45d90"
down_revision: str | Sequence[str] | None = "8c41a0b7e2d5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

NIL_WORKSPACE = "00000000-0000-0000-0000-000000000000"

role_enum = postgresql.ENUM("admin", "editor", "viewer", name="workspace_role", create_type=False)


def upgrade() -> None:
    role_enum.create(op.get_bind(), checkfirst=True)

    op.create_table(
        "workspace",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
    )
    op.create_table(
        "workspace_member",
        sa.Column(
            "workspace_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("workspace.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("actor", sa.Text(), nullable=False),
        sa.Column("role", role_enum, nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.PrimaryKeyConstraint("workspace_id", "actor", name="pk_workspace_member"),
    )
    op.create_index("ix_workspace_member_actor", "workspace_member", ["actor"])

    # The sentinel, provisioned. Every event written in Phase 0 and Phase 1 up to
    # this point already carries this id, so they all become rows of a real
    # workspace with no data rewritten.
    # The CAST is load-bearing: a bound Python str binds as VARCHAR, which
    # Postgres will not implicitly coerce to uuid on INSERT.
    op.execute(
        sa.text(
            "INSERT INTO workspace (id, name) VALUES (CAST(:id AS uuid), :name) "
            "ON CONFLICT (id) DO NOTHING"
        ).bindparams(id=NIL_WORKSPACE, name="Default workspace")
    )

    # --- row-level security -----------------------------------------------------
    op.execute("ALTER TABLE event_log ENABLE ROW LEVEL SECURITY")
    # FORCE so the policy also applies to the table's owner, which is the role the
    # application connects as on a hosted Postgres -- without it the policy is
    # decorative for exactly the connection that matters.
    op.execute("ALTER TABLE event_log FORCE ROW LEVEL SECURITY")
    op.execute(
        """
        CREATE POLICY event_log_workspace_isolation ON event_log
        USING (workspace_id = current_setting('atlas.workspace_id', true)::uuid)
        WITH CHECK (workspace_id = current_setting('atlas.workspace_id', true)::uuid)
        """
    )


def downgrade() -> None:
    op.execute("DROP POLICY IF EXISTS event_log_workspace_isolation ON event_log")
    op.execute("ALTER TABLE event_log NO FORCE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE event_log DISABLE ROW LEVEL SECURITY")
    op.drop_index("ix_workspace_member_actor", table_name="workspace_member")
    op.drop_table("workspace_member")
    op.drop_table("workspace")
    role_enum.drop(op.get_bind(), checkfirst=True)
