/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current Session
         * @description Who the browser is currently signed in as -- what the SPA asks on load so
         *     a returning PM isn't sent back through a login form they already passed.
         */
        get: operations["current_session_session_get"];
        put?: never;
        /**
         * Sign In
         * @description Exchange the shared passphrase plus a name for a signed session cookie.
         *
         *     Membership is checked here as well as on every later request: failing at the
         *     door with "you are not a member" beats issuing a session that 403s on
         *     everything the person then tries to do.
         */
        post: operations["sign_in_session_post"];
        /** Sign Out */
        delete: operations["sign_out_session_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feature-scopes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Feature Scopes
         * @description The left rail. Ordered by ingestion, oldest first -- the log's own order.
         */
        get: operations["list_feature_scopes_feature_scopes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feature-scopes/{feature_scope_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Feature Scope
         * @description The review page: every node and edge for one feature, flat and ungrouped.
         */
        get: operations["get_feature_scope_feature_scopes__feature_scope_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nodes/{node_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Node */
        post: operations["confirm_node_nodes__node_id__confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nodes/{node_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject Node */
        post: operations["reject_node_nodes__node_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nodes/{node_id}/edit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Edit Node */
        post: operations["edit_node_nodes__node_id__edit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feature-scopes/{feature_scope_id}/nodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Node
         * @description A claim the PM types in themselves (PRD R10).
         *
         *     `workspace_id` and `actor` come from the `Principal`, never the body --
         *     `add_node` takes fields rather than a Node so that is unreachable rather than
         *     merely unwritten (`docs/decisions/2026-08-03-manual-node-provenance.md`).
         */
        post: operations["add_node_feature_scopes__feature_scope_id__nodes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AddNodeRequest */
        AddNodeRequest: {
            type: components["schemas"]["NodeType"];
            /** Content */
            content: string;
        };
        /**
         * CreatedBy
         * @enum {string}
         */
        CreatedBy: "system" | "user";
        /**
         * Edge
         * @description A typed relationship between two Nodes (TRD Sec3.1).
         */
        Edge: {
            /**
             * Id
             * Format: uuid
             */
            id?: string;
            /**
             * From Node Id
             * Format: uuid
             */
            from_node_id: string;
            /**
             * To Node Id
             * Format: uuid
             */
            to_node_id: string;
            relation_type: components["schemas"]["RelationType"];
            /** Confidence Score */
            confidence_score: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
        };
        /** EditNodeRequest */
        EditNodeRequest: {
            /** Content */
            content: string;
        };
        /**
         * FeatureScope
         * @description The projected identity of one feature scope: what its UUID *means*.
         *
         *     `runs` is every `ingestion_run` that fed this scope, in append order -- a
         *     feature is assembled from many sources, which is what the UI's "assembled
         *     from" strip reads.
         *
         *     **`title` is the *first* run's** -- the one that opened the scope. This is a
         *     deliberate exception to the last-write-wins rule the rest of the projection
         *     follows, and slice 1C is what forced it: once a second *source* can join an
         *     existing scope, last-wins means adding a Jira ticket silently renames a
         *     feature a GitHub PR named, changing what a reviewer is looking at mid-review.
         *     A feature scope is named by the artifact it was opened from; later runs add
         *     evidence to it, they do not re-christen it. The cost is that re-ingesting a
         *     retitled PR keeps the original name, which is the lesser wrong -- and a
         *     rename, if ever wanted, should be a deliberate act with its own event rather
         *     than a side effect of ingestion.
         */
        FeatureScope: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Runs */
            runs: components["schemas"]["IngestionRunPayload"][];
        };
        /**
         * FeatureScopeDetail
         * @description One feature scope's projected state, as the review page reads it.
         *
         *     `feature_scope` is nullable because a scope ingested before slice 1A' has
         *     nodes but no `ingestion_run` event, and so no title. The UI renders that as
         *     an unnamed scope rather than being handed a fabricated one.
         */
        FeatureScopeDetail: {
            feature_scope: components["schemas"]["FeatureScope"] | null;
            /** Nodes */
            nodes: components["schemas"]["Node"][];
            /** Edges */
            edges: components["schemas"]["Edge"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * IngestionRunPayload
         * @description Payload of an `ingestion_run` Event -- what a feature scope *is*.
         *
         *     A feature scope is minted as a bare UUID by whatever triggers ingestion, and
         *     without this event the log records only that some nodes share that UUID:
         *     nothing names the feature, so the confirmation UI's left rail and page header
         *     have nothing to render and a reviewer navigates by raw UUID
         *     (`docs/architecture/Phase1_Architecture.md` Sec4.4).
         *
         *     Scope identity therefore lives *in the event log*, like everything else --
         *     not in a registry table or a name map inside the API. `title` is the
         *     human-facing name of the feature (the PR/issue title, as fetched); the
         *     `source_type`/`external_id`/`url` triple is the provenance of the run itself,
         *     the same shape a `SourceRef` carries for a Node. `external_id` fully
         *     qualifies the artifact within its source (`owner/repo#111`, not `111`),
         *     because a feature scope is workspace-global while a bare PR number is only
         *     unique inside one repository.
         *
         *     One scope can be fed by many runs -- that is the cross-source thesis (a
         *     feature assembled from GitHub *and* Jira), so the projection accumulates them
         *     rather than replacing. Slice 1D's per-run tool-call manifest
         *     (`docs/decisions/2026-07-28-extraction-tool-call-audit-logging.md`) lands
         *     here as an optional field, which replays cleanly over events written today;
         *     `extra="forbid"` means it arrives declared rather than smuggled in.
         */
        IngestionRunPayload: {
            /**
             * Feature Scope Id
             * Format: uuid
             */
            feature_scope_id: string;
            /** Title */
            title: string;
            source_type: components["schemas"]["SourceType"];
            /** External Id */
            external_id: string;
            /** Url */
            url: string;
            /** Tool Calls */
            tool_calls?: components["schemas"]["ToolCallRecord"][];
        };
        /**
         * Node
         * @description A typed knowledge element (TRD Sec3.1).
         *
         *     `source_refs` requires at least one entry: a Node without provenance is
         *     structurally impossible to construct, per CLAUDE.md's non-negotiable rule.
         */
        Node: {
            /**
             * Id
             * Format: uuid
             */
            id?: string;
            type: components["schemas"]["NodeType"];
            /** Content */
            content: string;
            /** Confidence Score */
            confidence_score?: number | null;
            /** @default unconfirmed */
            status: components["schemas"]["NodeStatus"];
            /** Source Refs */
            source_refs: components["schemas"]["SourceRef"][];
            /** @default system */
            created_by: components["schemas"]["CreatedBy"];
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at?: string;
            /** Updated By */
            updated_by?: string | null;
            /**
             * Workspace Id
             * Format: uuid
             */
            workspace_id: string;
            /**
             * Feature Scope Id
             * Format: uuid
             */
            feature_scope_id: string;
        };
        /**
         * NodeStatus
         * @enum {string}
         */
        NodeStatus: "unconfirmed" | "confirmed" | "edited" | "rejected";
        /**
         * NodeType
         * @enum {string}
         */
        NodeType: "goal" | "problem" | "evidence" | "decision" | "requirement" | "constraint" | "architecture_note" | "open_question" | "rejected_alternative";
        /**
         * RelationType
         * @enum {string}
         */
        RelationType: "supports" | "derives_from" | "conflicts_with" | "implements" | "rejects" | "depends_on";
        /**
         * Role
         * @description What a member may do in a workspace (TRD Sec9 -- RBAC at workspace level).
         *
         *     Three roles, and the split that matters is `VIEWER` vs. the rest: a viewer
         *     can read the extracted draft but cannot rule on it. That is the distinction
         *     the product actually needs, because a confirmation *is* the product's unit of
         *     truth -- "extraction is a draft until a human acts on it" means little if any
         *     reader can act. `ADMIN` differs from `EDITOR` only in managing the workspace
         *     itself (members, and connected sources when that surface arrives).
         *
         *     Feature-level scoping is explicitly Phase 4 (TRD Sec9); this is the workspace
         *     -level MVP and nothing more.
         * @enum {string}
         */
        Role: "admin" | "editor" | "viewer";
        /**
         * SignInRequest
         * @description `name` becomes the `actor` on every Event this person goes on to write --
         *     it is the audit record, not a display preference.
         */
        SignInRequest: {
            /** Passphrase */
            passphrase: string;
            /** Name */
            name: string;
        };
        /** SignInResponse */
        SignInResponse: {
            /** Actor */
            actor: string;
            role: components["schemas"]["Role"];
        };
        /**
         * SourceRef
         * @description A literal, provenance-bearing pointer into a source document (TRD Sec3.1).
         *
         *     `excerpt` is the specific text span that supports an extraction and is never
         *     stripped or normalized -- the eval harness verifies it appears verbatim in
         *     the raw source, so any mutation here would corrupt provenance.
         */
        SourceRef: {
            /**
             * Id
             * Format: uuid
             */
            id?: string;
            source_type: components["schemas"]["SourceType"];
            /** External Id */
            external_id: string;
            /** Url */
            url: string;
            /** Excerpt */
            excerpt: string;
            /**
             * Fetched At
             * Format: date-time
             */
            fetched_at?: string;
            /**
             * Workspace Id
             * Format: uuid
             */
            workspace_id: string;
        };
        /**
         * SourceType
         * @description Where a Node's evidence lives.
         *
         *     Every member but the last points *outward*, at an artifact in a connected
         *     tool. `HUMAN_ASSERTION` is the one that points at a person: it is the
         *     provenance of a node a human typed directly into Atlas (PRD R10 -- "a
         *     constraint mentioned verbally in a meeting"), where no artifact exists to
         *     cite. It is an addition to TRD Sec3.1's list, made deliberately -- see
         *     `docs/decisions/2026-08-03-manual-node-provenance.md`.
         *
         *     Without it, PRD R10 and CLAUDE.md's zero-exception "every Node carries a
         *     SourceRef" rule are jointly unsatisfiable, and the way that resolves in
         *     practice is a user pasting an unrelated URL to get past a required field --
         *     fabricated provenance, which is worse than none because it is
         *     indistinguishable from the real thing.
         * @enum {string}
         */
        SourceType: "github_pr" | "github_issue" | "github_commit" | "jira_ticket" | "notion_page" | "gdoc" | "human_assertion";
        /**
         * ToolCallRecord
         * @description One tool call an extraction run made -- or was refused (TRD Sec9 audit).
         *
         *     `Phase0_Architecture.md` Sec2 lists "every tool call is logged" as a guardrail
         *     alongside the call cap, and it was the one guardrail not implemented
         *     (`docs/decisions/2026-07-28-extraction-tool-call-audit-logging.md`). Without
         *     it the read-only, least-privilege promise is *enforced* by the permission
         *     gate but not **observable after the fact**, and observability is the whole
         *     point of a guardrail someone else has to trust.
         *
         *     `allowed = False` entries are the valuable ones: they are the record of the
         *     gate actually refusing something. Arguments are the agent's own (an issue
         *     number, a search string) -- never credentials, which live in the client and
         *     never pass through a tool call.
         */
        ToolCallRecord: {
            /** Tool */
            tool: string;
            /** Arguments */
            arguments?: {
                [key: string]: unknown;
            };
            /** Allowed */
            allowed: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    current_session_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignInResponse"];
                };
            };
        };
    };
    sign_in_session_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignInRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignInResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sign_out_session_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_feature_scopes_feature_scopes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureScope"][];
                };
            };
        };
    };
    get_feature_scope_feature_scopes__feature_scope_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                feature_scope_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureScopeDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_node_nodes__node_id__confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                node_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Node"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_node_nodes__node_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                node_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Node"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_node_nodes__node_id__edit_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                node_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditNodeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Node"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_node_feature_scopes__feature_scope_id__nodes_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                feature_scope_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddNodeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Node"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
