/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current Session
         * @description Who the browser is currently signed in as -- what the SPA asks on load so
         *     a returning PM isn't sent back through a login form they already passed.
         */
        get: operations["current_session_session_get"];
        put?: never;
        /**
         * Sign In
         * @description Exchange the shared passphrase plus a name for a signed session cookie.
         *
         *     Membership is checked here as well as on every later request: failing at the
         *     door with "you are not a member" beats issuing a session that 403s on
         *     everything the person then tries to do.
         */
        post: operations["sign_in_session_post"];
        /** Sign Out */
        delete: operations["sign_out_session_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Products
         * @description Every product in the caller's workspace, in creation order.
         *
         *     Feature scopes carry their own `product_id`, so grouping the rail happens on
         *     the client -- consistent with node ordering and the progress meter, which are
         *     presentation decisions the API deliberately does not make.
         */
        get: operations["list_products_products_get"];
        put?: never;
        /**
         * Create Product
         * @description Open a new product. The id is minted in `storage/`, never taken from the
         *     request -- same reason `add_node` builds its Node from fields.
         */
        post: operations["create_product_products_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{product_id}/description": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Describe Product
         * @description Say what this product is. `PUT` because the body states the field's whole
         *     value -- sending it twice leaves the same product, even though each send
         *     appends its own audit event.
         *
         *     Authored orientation, not an extracted claim: no provenance, no confirmation
         *     loop, and nothing here can reach a spec export
         *     (`docs/decisions/2026-08-19-product-orientation-rerun-safety-and-demo-data.md`
         *     decision 4).
         */
        put: operations["describe_product_products__product_id__description_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feature-scopes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Feature Scopes
         * @description The left rail. Ordered by ingestion, oldest first -- the log's own order.
         *
         *     Each row carries its own work-left counts. The alternative -- letting the
         *     client fetch every scope's full detail and count nodes itself -- means
         *     shipping every claim and excerpt of every feature to the browser to render
         *     a number in a sidebar, and it puts the definition of "unreviewed" in the
         *     frontend where three screens would each get their own copy of it.
         */
        get: operations["list_feature_scopes_feature_scopes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feature-scopes/{feature_scope_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Feature Scope
         * @description The review page: every node and edge for one feature, flat and ungrouped.
         */
        get: operations["get_feature_scope_feature_scopes__feature_scope_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feature-scopes/{feature_scope_id}/description": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Describe Feature Scope
         * @description Say what this feature is *for*.
         *
         *     Not a rename. The title stays the one the artifact that opened the scope
         *     gave it -- first-run-wins, per `storage/projections.py` -- so a reviewer
         *     keeps the name they recognise and gains the sentence saying why it exists.
         */
        put: operations["describe_feature_scope_feature_scopes__feature_scope_id__description_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{product_id}/connections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Connections
         * @description The Sources screen. Returns `ConnectionView`, which cannot carry a secret.
         */
        get: operations["list_connections_products__product_id__connections_get"];
        put?: never;
        /**
         * Connect Source
         * @description Verify a credential against the scope it claims, then store it encrypted.
         *
         *     The verification is not decoration. A credential that cannot see its own
         *     scope is rejected *here*, where the PM is still looking at the form and can
         *     fix it -- rather than at the first run, where the failure reads as "Atlas is
         *     broken". It also produces the access summary the flow spec asks for, so
         *     least privilege is demonstrated rather than asserted.
         *
         *     One round trip, not two: a "preview then save" pair would mean the browser
         *     holding the token across two requests, which is worse than checking it once
         *     on the way in.
         */
        post: operations["connect_source_products__product_id__connections_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connections/{connection_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke Connection
         * @description Revocation is a real delete -- the ciphertext stops existing. The event
         *     log keeps the record that it happened, which is the part that should.
         */
        delete: operations["revoke_connection_connections__connection_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{product_id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Runs
         * @description Run history for one product, oldest first -- the log's own order.
         */
        get: operations["list_runs_products__product_id__runs_get"];
        put?: never;
        /**
         * Start Ingestion
         * @description Accept an ingestion job and return before it finishes.
         *
         *     202, not 200: the run is *accepted*, and the id in the response is what the
         *     client polls. The `ingestion_run_started` event is written inside this
         *     request, so the job is already in the history the moment the response goes
         *     out -- and a run that dies on its first network call has still left a trace.
         *
         *     The credential is decrypted here, at the composition root, and handed to
         *     `pipeline` as an argument. Nothing in `pipeline/` or `ingestion/` knows where
         *     it came from, and the API process holds no ambient source credential of its
         *     own.
         */
        post: operations["start_ingestion_products__product_id__runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Run
         * @description What the client polls after a 202. State is derived, never stored.
         */
        get: operations["get_run_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nodes/{node_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Node */
        post: operations["confirm_node_nodes__node_id__confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nodes/{node_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject Node */
        post: operations["reject_node_nodes__node_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nodes/{node_id}/edit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Edit Node */
        post: operations["edit_node_nodes__node_id__edit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feature-scopes/{feature_scope_id}/nodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Node
         * @description A claim the PM types in themselves (PRD R10).
         *
         *     `workspace_id` and `actor` come from the `Principal`, never the body --
         *     `add_node` takes fields rather than a Node so that is unreachable rather than
         *     merely unwritten (`docs/decisions/2026-08-03-manual-node-provenance.md`).
         */
        post: operations["add_node_feature_scopes__feature_scope_id__nodes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AddNodeRequest */
        AddNodeRequest: {
            type: components["schemas"]["NodeType"];
            /** Content */
            content: string;
        };
        /**
         * ConnectSourceRequest
         * @description Connect one source to one product.
         *
         *     `secret` is the *only* field in this file that ever holds a credential, it
         *     only ever travels inbound, and nothing echoes it back -- the response is a
         *     `ConnectionView`, which has no field it could occupy.
         *
         *     `email` is required for Jira and meaningless for GitHub: Jira Cloud
         *     authenticates email + API token, GitHub authenticates the token alone. The
         *     endpoint validates that pairing rather than accepting a half-filled
         *     connection that would fail on its first run.
         */
        ConnectSourceRequest: {
            source_type: components["schemas"]["SourceType"];
            /** Host */
            host: string;
            /** Scope */
            scope: string;
            /** Secret */
            secret: string;
            /** Email */
            email?: string | null;
        };
        /**
         * ConnectionCreated
         * @description The stored connection, plus what its credential turned out to reach.
         *
         *     The access summary is the trust moment: a PM sees "Private repository · 12
         *     open issues" *before* Atlas is trusted with anything. It is shown and
         *     discarded -- never stored, because it is a fact about right now, not
         *     provenance.
         */
        ConnectionCreated: {
            connection: components["schemas"]["ConnectionView"];
            /** Access Label */
            access_label: string;
            /** Access Detail */
            access_detail: string;
        };
        /**
         * ConnectionView
         * @description What an endpoint may say about a connection. The whole of it.
         *
         *     There is no `secret` field, no `ciphertext` field, and no `Any`-typed extras
         *     bag — so a secret cannot reach a response by someone forgetting to exclude
         *     it. `tests/test_connections.py` asserts that absence directly, and
         *     `tests/test_api.py` asserts it again over the generated OpenAPI schema, which
         *     is what the frontend's types are built from.
         */
        ConnectionView: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Product Id
             * Format: uuid
             */
            product_id: string;
            source_type: components["schemas"]["SourceType"];
            /** Account */
            account: string;
            /** Host */
            host: string;
            /** Scope */
            scope: string;
            /** Secret Hint */
            secret_hint: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Created By */
            created_by: string;
            /** Last Used At */
            last_used_at?: string | null;
        };
        /** CreateProductRequest */
        CreateProductRequest: {
            /** Name */
            name: string;
        };
        /**
         * CreatedBy
         * @enum {string}
         */
        CreatedBy: "system" | "user";
        /**
         * DescribeRequest
         * @description What a product or a feature is, in the PM's own words (slice 3).
         *
         *     `DescriptionStr` rather than `NonBlankStr`, and that is the whole difference:
         *     an empty description is not a malformed one, it is how a wrong description is
         *     removed. The length bound is the domain's own, reused rather than restated at
         *     the wire.
         */
        DescribeRequest: {
            /** Description */
            description: string;
        };
        /**
         * Edge
         * @description A typed relationship between two Nodes (TRD Sec3.1).
         */
        Edge: {
            /**
             * Id
             * Format: uuid
             */
            id?: string;
            /**
             * From Node Id
             * Format: uuid
             */
            from_node_id: string;
            /**
             * To Node Id
             * Format: uuid
             */
            to_node_id: string;
            relation_type: components["schemas"]["RelationType"];
            /** Confidence Score */
            confidence_score: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
        };
        /** EditNodeRequest */
        EditNodeRequest: {
            /** Content */
            content: string;
        };
        /**
         * FeatureScope
         * @description The projected identity of one feature scope: what its UUID *means*.
         *
         *     `runs` is every `ingestion_run` that fed this scope, in append order -- a
         *     feature is assembled from many sources, which is what the UI's "assembled
         *     from" strip reads.
         *
         *     **`title` is the *first* run's** -- the one that opened the scope. This is a
         *     deliberate exception to the last-write-wins rule the rest of the projection
         *     follows, and slice 1C is what forced it: once a second *source* can join an
         *     existing scope, last-wins means adding a Jira ticket silently renames a
         *     feature a GitHub PR named, changing what a reviewer is looking at mid-review.
         *     A feature scope is named by the artifact it was opened from; later runs add
         *     evidence to it, they do not re-christen it. The cost is that re-ingesting a
         *     retitled PR keeps the original name, which is the lesser wrong -- and a
         *     rename, if ever wanted, should be a deliberate act with its own event rather
         *     than a side effect of ingestion.
         */
        FeatureScope: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Runs */
            runs: components["schemas"]["IngestionRunPayload"][];
            /** Product Id */
            product_id?: string | null;
            /** Description */
            description?: string | null;
        };
        /**
         * FeatureScopeDetail
         * @description One feature scope's projected state, as the review page reads it.
         *
         *     `feature_scope` is nullable because a scope ingested before slice 1A' has
         *     nodes but no `ingestion_run` event, and so no title. The UI renders that as
         *     an unnamed scope rather than being handed a fabricated one.
         */
        FeatureScopeDetail: {
            feature_scope: components["schemas"]["FeatureScope"] | null;
            /** Nodes */
            nodes: components["schemas"]["Node"][];
            /** Edges */
            edges: components["schemas"]["Edge"][];
        };
        /**
         * FeatureScopeRow
         * @description One row of a feature list: the scope's identity plus how much of it is
         *     still work.
         *
         *     A separate envelope from the `FeatureScope` projection dataclass because the
         *     two answer different questions -- that one is identity, this one is identity
         *     *and* state as of now. Composed rather than flattened so the counts stay
         *     recognisably derived, and so adding a fourth number later touches one place.
         */
        FeatureScopeRow: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Runs */
            runs: components["schemas"]["IngestionRunPayload"][];
            /** Product Id */
            product_id: string | null;
            counts: components["schemas"]["ScopeCounts"];
            /** Description */
            description: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * IngestionRunPayload
         * @description Payload of an `ingestion_run` Event -- what a feature scope *is*.
         *
         *     A feature scope is minted as a bare UUID by whatever triggers ingestion, and
         *     without this event the log records only that some nodes share that UUID:
         *     nothing names the feature, so the confirmation UI's left rail and page header
         *     have nothing to render and a reviewer navigates by raw UUID
         *     (`docs/architecture/Phase1_Architecture.md` Sec4.4).
         *
         *     Scope identity therefore lives *in the event log*, like everything else --
         *     not in a registry table or a name map inside the API. `title` is the
         *     human-facing name of the feature (the PR/issue title, as fetched); the
         *     `source_type`/`external_id`/`url` triple is the provenance of the run itself,
         *     the same shape a `SourceRef` carries for a Node. `external_id` fully
         *     qualifies the artifact within its source (`owner/repo#111`, not `111`),
         *     because a feature scope is workspace-global while a bare PR number is only
         *     unique inside one repository.
         *
         *     One scope can be fed by many runs -- that is the cross-source thesis (a
         *     feature assembled from GitHub *and* Jira), so the projection accumulates them
         *     rather than replacing. Slice 1D's per-run tool-call manifest
         *     (`docs/decisions/2026-07-28-extraction-tool-call-audit-logging.md`) lands
         *     here as an optional field, which replays cleanly over events written today;
         *     `extra="forbid"` means it arrives declared rather than smuggled in.
         */
        IngestionRunPayload: {
            /**
             * Feature Scope Id
             * Format: uuid
             */
            feature_scope_id: string;
            /** Title */
            title: string;
            source_type: components["schemas"]["SourceType"];
            /** External Id */
            external_id: string;
            /** Url */
            url: string;
            /** Tool Calls */
            tool_calls?: components["schemas"]["ToolCallRecord"][];
            /** Product Id */
            product_id?: string | null;
            /** Run Id */
            run_id?: string | null;
        };
        /**
         * Node
         * @description A typed knowledge element (TRD Sec3.1).
         *
         *     `source_refs` requires at least one entry: a Node without provenance is
         *     structurally impossible to construct, per CLAUDE.md's non-negotiable rule.
         */
        Node: {
            /**
             * Id
             * Format: uuid
             */
            id?: string;
            type: components["schemas"]["NodeType"];
            /** Content */
            content: string;
            /** Confidence Score */
            confidence_score?: number | null;
            /** @default unconfirmed */
            status: components["schemas"]["NodeStatus"];
            /** Source Refs */
            source_refs: components["schemas"]["SourceRef"][];
            /** @default system */
            created_by: components["schemas"]["CreatedBy"];
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at?: string;
            /** Updated By */
            updated_by?: string | null;
            /**
             * Workspace Id
             * Format: uuid
             */
            workspace_id: string;
            /**
             * Feature Scope Id
             * Format: uuid
             */
            feature_scope_id: string;
        };
        /**
         * NodeStatus
         * @enum {string}
         */
        NodeStatus: "unconfirmed" | "confirmed" | "edited" | "rejected";
        /**
         * NodeType
         * @enum {string}
         */
        NodeType: "goal" | "problem" | "evidence" | "decision" | "requirement" | "constraint" | "architecture_note" | "open_question" | "rejected_alternative";
        /**
         * Product
         * @description One product a PM works on -- its own GitHub org, its own Jira site.
         *
         *     A product is a projection, not a table, for the same reason feature-scope
         *     identity is (slice 1A'): the event log is the source of truth and adding a
         *     table would put state outside it. It is deliberately *not* derived from
         *     ingested data such as `external_id` -- a product has to exist before the
         *     first connection is made to it, so it cannot be inferred from the results of
         *     ingestion that has not happened yet.
         */
        Product: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
        };
        /**
         * RelationType
         * @enum {string}
         */
        RelationType: "supports" | "derives_from" | "conflicts_with" | "implements" | "rejects" | "depends_on";
        /**
         * Role
         * @description What a member may do in a workspace (TRD Sec9 -- RBAC at workspace level).
         *
         *     Three roles, and the split that matters is `VIEWER` vs. the rest: a viewer
         *     can read the extracted draft but cannot rule on it. That is the distinction
         *     the product actually needs, because a confirmation *is* the product's unit of
         *     truth -- "extraction is a draft until a human acts on it" means little if any
         *     reader can act. `ADMIN` differs from `EDITOR` only in managing the workspace
         *     itself (members, and connected sources when that surface arrives).
         *
         *     Feature-level scoping is explicitly Phase 4 (TRD Sec9); this is the workspace
         *     -level MVP and nothing more.
         * @enum {string}
         */
        Role: "admin" | "editor" | "viewer";
        /**
         * RunState
         * @description A run's derived state -- never stored, always replayed.
         *
         *     `INTERRUPTED` is the honest one. Ingestion started from the UI runs in the API
         *     process (no task queue -- an explicit CLAUDE.md Non-Goal), so a process that
         *     dies mid-run leaves a start event with no terminal event, which is
         *     indistinguishable from a run that is merely slow. Rather than report that as
         *     "running" forever, a start older than `INTERRUPTED_AFTER` with no terminal
         *     event is reported as interrupted: fail-visible, the same instinct that makes
         *     an unscoped query return zero rows instead of an error.
         * @enum {string}
         */
        RunState: "running" | "succeeded" | "failed" | "interrupted";
        /**
         * RunTargetKind
         * @description How a run's `target` string should be read.
         *
         *     Scoped ingestion (TRD Sec4.2) is *deliberate*: a run names one PR, one issue,
         *     one epic's children or one label -- never "everything in this project". The
         *     kind is what the API validates against, so the UI cannot ask for a crawl by
         *     sending a target the CLI would have refused.
         * @enum {string}
         */
        RunTargetKind: "github_pr" | "jira_issue" | "jira_epic" | "jira_label";
        /**
         * RunView
         * @description One run, as the Sources screen reads it.
         *
         *     `state` is resolved here, at read time, because one of its four values is a
         *     function of *now* -- a start with no terminal event older than
         *     `INTERRUPTED_AFTER` is interrupted, not running.
         */
        RunView: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Feature Scope Id
             * Format: uuid
             */
            feature_scope_id: string;
            /** Product Id */
            product_id: string | null;
            /** Connection Id */
            connection_id: string | null;
            target_kind: components["schemas"]["RunTargetKind"];
            /** Target */
            target: string;
            state: components["schemas"]["RunState"];
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Started By */
            started_by: string;
            /** Finished At */
            finished_at?: string | null;
            /** Error */
            error?: string | null;
            /**
             * Artifacts
             * @default 0
             */
            artifacts: number;
            /**
             * Nodes
             * @default 0
             */
            nodes: number;
            /**
             * Edges
             * @default 0
             */
            edges: number;
        };
        /**
         * ScopeCounts
         * @description How much of one feature still needs a human.
         *
         *     Deliberately *not* a field on `FeatureScope`: that dataclass is the scope's
         *     identity -- what its UUID means -- and identity does not change when someone
         *     confirms a claim. These are derived aggregates over Nodes and Edges, and
         *     keeping them apart stops the identity record from looking mutable.
         *
         *     Computed in `storage/` rather than in the browser because three surfaces
         *     need the same number (the feature list, the Conflicts nav entry, the product
         *     dashboard), and because deriving it client-side means shipping every node
         *     and edge of every feature to the browser in order to count them.
         */
        ScopeCounts: {
            /** Total */
            total: number;
            /** Unreviewed */
            unreviewed: number;
            /** Conflicts */
            conflicts: number;
        };
        /**
         * SignInRequest
         * @description `name` becomes the `actor` on every Event this person goes on to write --
         *     it is the audit record, not a display preference.
         */
        SignInRequest: {
            /** Passphrase */
            passphrase: string;
            /** Name */
            name: string;
        };
        /** SignInResponse */
        SignInResponse: {
            /** Actor */
            actor: string;
            role: components["schemas"]["Role"];
        };
        /**
         * SourceRef
         * @description A literal, provenance-bearing pointer into a source document (TRD Sec3.1).
         *
         *     `excerpt` is the specific text span that supports an extraction and is never
         *     stripped or normalized -- the eval harness verifies it appears verbatim in
         *     the raw source, so any mutation here would corrupt provenance.
         */
        SourceRef: {
            /**
             * Id
             * Format: uuid
             */
            id?: string;
            source_type: components["schemas"]["SourceType"];
            /** External Id */
            external_id: string;
            /** Url */
            url: string;
            /** Excerpt */
            excerpt: string;
            /**
             * Fetched At
             * Format: date-time
             */
            fetched_at?: string;
            /**
             * Workspace Id
             * Format: uuid
             */
            workspace_id: string;
        };
        /**
         * SourceType
         * @description Where a Node's evidence lives.
         *
         *     Every member but the last points *outward*, at an artifact in a connected
         *     tool. `HUMAN_ASSERTION` is the one that points at a person: it is the
         *     provenance of a node a human typed directly into Atlas (PRD R10 -- "a
         *     constraint mentioned verbally in a meeting"), where no artifact exists to
         *     cite. It is an addition to TRD Sec3.1's list, made deliberately -- see
         *     `docs/decisions/2026-08-03-manual-node-provenance.md`.
         *
         *     Without it, PRD R10 and CLAUDE.md's zero-exception "every Node carries a
         *     SourceRef" rule are jointly unsatisfiable, and the way that resolves in
         *     practice is a user pasting an unrelated URL to get past a required field --
         *     fabricated provenance, which is worse than none because it is
         *     indistinguishable from the real thing.
         * @enum {string}
         */
        SourceType: "github_pr" | "github_issue" | "github_commit" | "jira_ticket" | "notion_page" | "gdoc" | "human_assertion";
        /**
         * StartRunRequest
         * @description Pull one target into a feature -- a new one, or one that already exists.
         *
         *     Naming an existing `feature_scope_id` is what makes a feature cross-source:
         *     the run is handed the claims the other source already produced, so a
         *     contradiction between them becomes a `conflicts_with` edge instead of two
         *     unaware halves.
         */
        StartRunRequest: {
            /**
             * Connection Id
             * Format: uuid
             */
            connection_id: string;
            target_kind: components["schemas"]["RunTargetKind"];
            /** Target */
            target: string;
            /** Feature Scope Id */
            feature_scope_id?: string | null;
            /**
             * Limit
             * @default 10
             */
            limit: number;
        };
        /**
         * ToolCallRecord
         * @description One tool call an extraction run made -- or was refused (TRD Sec9 audit).
         *
         *     `Phase0_Architecture.md` Sec2 lists "every tool call is logged" as a guardrail
         *     alongside the call cap, and it was the one guardrail not implemented
         *     (`docs/decisions/2026-07-28-extraction-tool-call-audit-logging.md`). Without
         *     it the read-only, least-privilege promise is *enforced* by the permission
         *     gate but not **observable after the fact**, and observability is the whole
         *     point of a guardrail someone else has to trust.
         *
         *     `allowed = False` entries are the valuable ones: they are the record of the
         *     gate actually refusing something. Arguments are the agent's own (an issue
         *     number, a search string) -- never credentials, which live in the client and
         *     never pass through a tool call.
         */
        ToolCallRecord: {
            /** Tool */
            tool: string;
            /** Arguments */
            arguments?: {
                [key: string]: unknown;
            };
            /** Allowed */
            allowed: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    current_session_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignInResponse"];
                };
            };
        };
    };
    sign_in_session_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignInRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignInResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sign_out_session_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_products_products_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"][];
                };
            };
        };
    };
    create_product_products_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProductRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    describe_product_products__product_id__description_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DescribeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_feature_scopes_feature_scopes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureScopeRow"][];
                };
            };
        };
    };
    get_feature_scope_feature_scopes__feature_scope_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                feature_scope_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureScopeDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    describe_feature_scope_feature_scopes__feature_scope_id__description_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                feature_scope_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DescribeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureScope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_connections_products__product_id__connections_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    connect_source_products__product_id__connections_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConnectSourceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_connection_connections__connection_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connection_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_products__product_id__runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_ingestion_products__product_id__runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_node_nodes__node_id__confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                node_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Node"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_node_nodes__node_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                node_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Node"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_node_nodes__node_id__edit_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                node_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditNodeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Node"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_node_feature_scopes__feature_scope_id__nodes_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                feature_scope_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddNodeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Node"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
